const navContent = () => {
  const aboutKrisat = {
    content:
      "</br><p>Krishna College of Agriculture and Technology(KRISAT) has been set with a mission to meet the growing demand for Agro-based food production globally across India and the world using the latest technology in food production.</p><p>With the increased demand for well-trained farm scientists to translate the latest technologies into reality in sustainable food, feed, fibre and fuel (biomass) production, we are prominent in budding smart agriculture professionals to meet the current and future food demands</p><p>With India opening its gate to WTO’s GATT and the Prime Minister’s Mission to enhance “Make in India” or the Reserve Bank Governor’s “Make for India” focus, there is an immense opportunity for local marketing within the country as well as export of value-added agricultural products to different countries of the world. For sustainable processing and value addition of farm produce, a number of new agro processing industries have to be developed in rural areas and this requires additional trained agricultural technologist and Agri-business experts.</p><p>Thus, Krishna College of Agriculture and Technology(KRISAT) aims at creating agricultural graduates with latest technology and inputs to create Green Revolution all over.</p>",
  };
  const missViss = {
    content:
      "</br><h2>Vision</h2><p>KRISAT’S vision is to provide technical education and skill development using modern and latest equipment to meet International standards.We envision a future where India leads the world in agricultural innovation and sustainability. Our commitment is steadfast, aiming to:</p><ul><li><b>Empower India's Agricultural Innovation: </b>As an Agriculture Ambassador, we empower our students and stakeholders to contribute meaningfully to the advancement of Agriculture.</li><li><b>Preserve the Health of Our Ecosystems: </b>We recognize the intrinsic link between the health of our land, water, air, and soil and the well-being of future generations.</li><li><b>Educate Farmers with Innovative Methods: </b>Our methods are not just theoretical; they are tried, tested, and tailored to the unique challenges facing modern Agriculture. These enhance profitability for the local farmers.</li><li><b>Foster International Collaboration: </b>Recognizing the value of global exchange and collaboration, through Tamil Nadu Agricultural University (TNAU), we actively engage with international institutions to share knowledge, expertise, and best practices.</li></ul></br><h2>Mission</h2><p>KRISAT's mission is to empower Agripreneurs through:</p><ul><li><b>Diverse Organic Farming Methods: </b>Tamil Nadu Agricultural University's (TNAU's) curriculum emphasizes hands-on experience in organic farming techniques. From permaculture to agroforestry, we explore a spectrum of farming practices, equipping our students with versatile tools to navigate modern agriculture.</li><li><b>Integration of Ancient and Modern Innovations: </b> Drawing from the wisdom of traditional farming practices and leveraging the latest technological advancements, allows us to cater to two fundamental principles: nurturing the health of our planet and safeguarding the prosperity of our farmers</li><li><b>Social Media Advocacy: </b> Through informative videos and posts, we leverage the power of social media to spread awareness about sustainable farming practices, bringing a positive change within our farming communities, stakeholders, as well as the public</li><li><b>Holistic Development: </b>Beyond technical expertise, we prioritize the holistic development of our students, fostering their leadership skills, communication skills, entrepreneurial spirit, social responsibility, and overall personality development.</li></ul>",
  };
  const govCoun = {
    content:
      "<ul><li>K Chandrasekar - Chairman</li><li>C Rajendran, IAS (Retd), formerly Addl. Secretary of Agriculture, Tamil Nadu Government</li><li>K Seenivasan, B, Sc. FCA Auditor</li><li>C Manivannan, Industrialist</li><li>Dr Siva, MBBS</li><li>Asst Director of Agriculture, Usilampatty,Madurai (Presently Mr.Thanuskodi,B.Sc.(Agric.))</li><li>Dr R Seenivasan, M. Sc. (Agri), Ph.D, Dy. General Manager, TNPL, Karur</li><li>Dr.V.Swaminathan, Professor and Head, Department of Horticulture, Agricultural College and Research Institute, TNAU, Madurai- 625104</li><li>Dr.V.K.Paulpandi, Ph.D., Professor and Head, Regional Research Station, Tamil Nadu Agricultural University, Aruppukkottai - 639117</li><li>The Dean, Agricultural College and Research Institute, Madurai- 625104 (presently Dr S Raghupathy, Ph.D.)</li><li>C Swaminathan, Dean, KRISAT (Ex. Officio Member) - Member Secretary</li></ul>",
  };
  const prinDsk = {
    content:
      "</br><p>I hope this message finds you in good health and high spirits as we embark on another promising academic year at KRISAT. As the Principal, I am delighted to welcome both new and returning students to our vibrant and inclusive learning community</p><p> At KRISAT, we work hard to create a supportive community that encourages students' academic and personal development and helps them become ready for a bright future. To meet the needs of the evolving world KRISAT is dedicated to providing you with numerous educational options so that you may pursue and achieve success in whatever area of study most interests you, be it technology, the arts, business, or something else entirely.</p><p>The campus is spread out over a wide area of 140 acres, giving the impression of a valley due to the surrounding hills. The property is covered in lush green vegetation, including herbs, trees, and climbers, which serves as a habitat for a wide variety of animals, including birds, reptiles, amphibians, butterflies, and honey bees. Overall, the campus has a pure aesthetic look.</p><p>The campus has invested in state-of-the-art technology, updated classrooms, state-of-the-art research labs, and innovative communal areas to foster your academic success. You'll be able to fully engage in hands-on learning thanks to the tools at your disposal. Our highly regarded professors are not only well-versed in their subjects but also enthusiastic guides who care deeply about your development as a thinker. They will help you succeed by pointing you in the right direction, getting you thinking critically, and mentoring you along the way.</p><p>We know that your health and happiness are important to your academic performance. Comprehensive counselling, career assistance, health services, and extracurricular activities are just some of the ways in which our enhanced student support services aim to improve your college experience and help you strike a good work-life balance. Moreover, cultural, social, and intellectual events will be planned throughout the year to help you make friends, learn about others' cultures, and broaden your own.</p><p>Please take use of these possibilities, push yourself, and make the most of your time in college. All of the teachers, staff, and auxiliary resources at our institution are committed to helping you succeed. Let's embrace the tenacity, curiosity, and cooperation that make our college special as we begin a new academic year. Together, I know that we can make a difference in the world and accomplish incredible things.I wish you all a successful and rewarding year ahead. May your journey at KRISAT be filled with transformative experiences, personal growth, and lifelong friendships.</p><p>I wish you all a successful and rewarding year ahead. May your journey at KRISAT be filled with transformative experiences, personal growth, and lifelong friendships.</p></br><p>Sincerely,</br> <b>Dr. V.K. Paulpandi</b></p>",
  };
  const crsOff = {
    content:
      "</br><h2>B.Sc. (Hons) Agriculture</h2><h4>Course Duration: 4 years</h4></br><p>The foundation course in Agriculture is infused with hands-on training at our agricultural field. This base course lays a strong foundation in expanding your knowledge with well trained farm scientist to meet productive food demands.</p>",
  };

  return {
    aboutKrisat,
    missViss,
    govCoun,
    prinDsk,
    crsOff,
  };
};

export default navContent;
